package database

import (
	"database/sql"
	"fmt"
)

// Phase 23 extends profile-owned game saves with a small preview image payload.
// The preview is generated by the browser from the emulator canvas and follows
// the exact same profile/game identity as save state and SRAM data. Keeping it
// in the existing versioned save catalog makes backup/recovery behavior and the
// Games save gallery deterministic without putting binary payloads in SQLite.
func migratePhase23(db *sql.DB) error {
	tx, err := db.Begin()
	if err != nil {
		return fmt.Errorf("migrate phase23 begin: %w", err)
	}
	defer tx.Rollback()

	const rebuild = `
ALTER TABLE game_saves RENAME TO game_saves_phase21;

CREATE TABLE game_saves (
    profile_id INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    kind TEXT NOT NULL,
    slot INTEGER NOT NULL DEFAULT 0,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(profile_id, game_id, kind, slot),
    FOREIGN KEY(profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    FOREIGN KEY(game_id) REFERENCES games(id) ON DELETE CASCADE,
    CHECK(kind IN ('state','sram','preview')),
    CHECK(slot >= 0 AND slot <= 9),
    CHECK(size_bytes >= 0),
    CHECK(version >= 1)
);

INSERT INTO game_saves(profile_id,game_id,kind,slot,size_bytes,version,updated_at)
SELECT profile_id,game_id,kind,slot,size_bytes,version,updated_at
FROM game_saves_phase21;

DROP TABLE game_saves_phase21;

CREATE INDEX idx_game_saves_profile_updated
    ON game_saves(profile_id, updated_at DESC, game_id, kind, slot);
CREATE INDEX idx_game_saves_game
    ON game_saves(game_id, profile_id, kind, slot);
`
	if _, err := tx.Exec(rebuild); err != nil {
		return fmt.Errorf("migrate phase23 game save previews: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("migrate phase23 commit: %w", err)
	}
	return nil
}
